name: Docker Sync Library

on:
#  push:
#    branches: [ main ]

  workflow_dispatch:

  schedule:
    - cron: '0 21 * * *'

jobs:
  sync_nginx:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "latest"
          - "stable"
          - "alpine"
          - "stable-alpine"
          - "1.27"
          - "1.27-alpine"
          - "1.26"
          - "1.26-alpine"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync nginx:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: docker.io/library/nginx:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/nginx:${{ matrix.version }}

  sync_mysql:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "latest"
          - "lts"
          - "8"
          - "8.4"
          - "8.4.3"
          - "8.4-oracle"
          - "8.4.3-oracle"
          - "8.0"
          - "8.0.40"
          - "8.0-oracle"
          - "8.0.40-oracle"
          - "8.0-debian"
          - "8.0.40-debian"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync mysql:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: docker.io/library/mysql:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/mysql:${{ matrix.version }}

  sync_redis:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "latest"
          - "alpine"
          - "6"
          - "6-alpine"
          - "6.2"
          - "6.2-alpine"
          - "7"
          - "7-alpine"
          - "7.2"
          - "7.2-alpine"
          - "7.4"
          - "7.4-alpine"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync redis:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: docker.io/library/redis:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/redis:${{ matrix.version }}

  sync_php:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync php:${{ matrix.version }}-cli
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: docker.io/library/php:${{ matrix.version }}-cli
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:${{ matrix.version }}-cli

      - name: sync php:${{ matrix.version }}-fpm
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: docker.io/library/php:${{ matrix.version }}-fpm
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:${{ matrix.version }}-fpm

      - name: sync php:${{ matrix.version }}-cli-alpine
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: docker.io/library/php:${{ matrix.version }}-cli-alpine
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:${{ matrix.version }}-cli-alpine

      - name: sync php:${{ matrix.version }}-fpm-alpine
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: docker.io/library/php:${{ matrix.version }}-fpm-alpine
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/php:${{ matrix.version }}-fpm-alpine

  sync_vaultwarden_server:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "latest"
          - "alpine"
          - "1.32.5"
          - "1.32.5-alpine"
          - "1.32.6"
          - "1.32.6-alpine"

    steps:
      - name: login to aliyuncs
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: sync vaultwarden/server:${{ matrix.version }}
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: docker.io/vaultwarden/server:${{ matrix.version }}
          dst: |
            ${{ secrets.ALI_DOCKER_REPO }}/mirrors_hub/vaultwarden_server:${{ matrix.version }}
